### ISSUE TITLE
Pe4ch's Blog

### ISSUE THREAD

**Issue by su-pe4ch** [MliKiowa/BlogFriend#8]
```json
{
"title": "Pe4ch's Blog",
"keywords": ["个人博客"],
"url": "https://www.yxyink.com",
"description": "日复一日，必有精进。",
"avatar": "https://www.yxyink.com/images/icon.png"
}
```

**Comment by MliKiowa** [comment]
LightHouse Testing Ok,Then Go [there](https://friend.nanaeo.cn/test/site–8.html)

**Comment by MliKiowa** [comment]
**👋 请及时添加本站友链**
距离成功只剩一步之遥了，请把本站添加到您的友链中，然后再下方评论告知。

**Comment by MliKiowa** [comment]
**🎉 恭喜，友链添加成功！**
稍后片刻刷新网页就可以看到您的链接。
> 如果您的站点信息发生了变动，请直接修改这个 issue 的内容。
